name: Weekly Data Update

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bun-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install and build source files
        run: bun run build

      - name: Detect data changes
        id: changes
        run: |
          if git diff -U0 --no-color -- dist/all-postcodes.json; then
            echo "No changes detected"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected:"
            git diff --stat
            echo ""
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PR_BOT_TOKEN }}
          commit-message: 'chore: data update'
          title: 'chore: data update'
          body: |
            Automated data update.
          branch: chore/data-update
          delete-branch: true
          labels: data-update

      - name: No changes
        if: steps.changes.outputs.changed == 'false'
        run: echo "No data updates found."
